class UserAlreadyExistsError(Exception):
    """User already exists exception"""
